POST http://localhost:3000/reports/
Content-Type: application/json

{
    "make": "GM",
    "model":"Chevette",
    "year": 1992,
    "mileage": 400500,
    "lng":0,
    "lat":0,
    "price":3000
}

###
PATCH  http://localhost:3000/reports/6
Content-Type: application/json

{
    "approved": true
}